# Generated by Django 4.1.2 on 2022-10-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('CategoriaId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoriaName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('ComentarioId', models.AutoField(primary_key=True, serialize=False)),
                ('LugarId', models.CharField(max_length=100)),
                ('UsuarioId', models.CharField(max_length=100)),
                ('Comentario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('HistoricoId', models.AutoField(primary_key=True, serialize=False)),
                ('LugarId', models.CharField(max_length=100)),
                ('UsuarioId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesPublicadas',
            fields=[
                ('ImagenId', models.AutoField(primary_key=True, serialize=False)),
                ('LugarId', models.CharField(max_length=100)),
                ('UsuarioId', models.CharField(max_length=100)),
                ('UrlImagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('LugarId', models.AutoField(primary_key=True, serialize=False)),
                ('LugarName', models.CharField(max_length=100)),
                ('CategoriaId', models.CharField(max_length=100)),
                ('Coordenadas', models.CharField(max_length=100)),
                ('CiudadId', models.CharField(max_length=100)),
                ('CodigoPostal', models.CharField(max_length=100)),
                ('Horario', models.CharField(max_length=100)),
                ('LugarStatus', models.CharField(max_length=100)),
                ('Servicios', models.CharField(max_length=100)),
                ('UrlImagen', models.CharField(max_length=100)),
                ('Likes', models.BigIntegerField()),
                ('Dislikes', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('UsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('UsuarioName', models.CharField(max_length=100)),
                ('UsuarioApellidos', models.CharField(max_length=100)),
                ('UsuarioEmail', models.CharField(max_length=100)),
                ('UsuarioPassword', models.CharField(max_length=100)),
                ('UsuarioTelefono', models.CharField(max_length=10)),
                ('UsuarioStatus', models.CharField(max_length=100)),
                ('UrlImagen', models.CharField(max_length=100)),
            ],
        ),
    ]
